// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Warranty_System.Models;

public partial class OrderDetails
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? Stt { get; set; }

    public int? ProductId { get; set; }

    public decimal? Quantity { get; set; }
}