// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Warranty_System.Models;

public partial class Orders
{
    public int Id { get; set; }

    public string? CustomerName { get; set; }

    public string? CustomerPhoneNumber { get; set; }

    public string? CustomerAddress { get; set; }

    public DateTime? CreatedDate { get; set; }
}