// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Warranty_System.Models;

public partial class RefreshTokens
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Token { get; set; } = null!;

    public DateTime? CreatedDate { get; set; }

    public DateTime? ExpireDate { get; set; }

    /// <summary>
    /// 0 = active, 1 = revoked (invalidated)
    /// </summary>
    public bool? IsRevoked { get; set; }
}