// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Warranty_System.Models;

public partial class Serials
{
    public int Id { get; set; }

    public string? ProductSerial { get; set; }

    public int? ProductId { get; set; }
}