// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Warranty_System.Models;

public partial class SpareParts
{
    public int Id { get; set; }

    public int? SparePartGroupId { get; set; }

    public int? ProductId { get; set; }

    public int? UnitId { get; set; }

    public string? SparePartNumber { get; set; }

    public string? Description { get; set; }

    public decimal? Price { get; set; }
}